trigger:
- master

resources:
- repo: self

variables:
  system.debug: true
  dockerHubServiceConnection: 'DockerHubConnection'
  imageRepository: 'mart800749/MicroservicesDevOps'
  tag: '$(Build.BuildId)'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  displayName: 'Build and push image to Docker Hub'
  steps:
  - task: Docker@2
    displayName: 'Build an image'
    inputs:
      command: build
      # Especificamos la ruta correcta al Dockerfile
      dockerfile: 'Servicios.api.Gateway/Dockerfile'
      # El contexto es la raíz del repositorio
      context: '.' 
      arguments: '--no-cache'
      repository: $(imageRepository)
      tags: |
        $(tag)

  - task: Docker@2
    displayName: 'Push the image to Docker Hub'
    inputs:
      command: push
      repository: $(imageRepository)
      containerRegistry: $(dockerHubServiceConnection)
      tags: |
        $(tag)
