apiVersion: v1
kind: Pod
metadata:
  name: gateway-pod
  namespace: production
  labels:
    app: gateway
    type: microservice
spec:
  containers:
  - name: gateway-app
    image: $(gatewayImage)
    ports:
    - containerPort: 80