apiVersion: v1
kind: Pod
metadata:
  name: microservice-seguridad-pod
  labels:
    app: microservice-seguridad
    type: microservice
spec:
  containers:
  - name: microservice-seguridad-app
    image: mart800749/serviciosapiseguridad:latest
    ports:
    - containerPort: 80
    env:
        - name: ConnectionStrings__ConexionDB
          value: "Server=mssql-service;Initial Catalog=Seguridad;User Id=sa;Password=VaxiDrez2025!;TrustServerCertificate=True;"  
