apiVersion: v1
kind: Service
metadata:
  name: mssql-service
  namespace: production
  labels:
    name: mssql-service
    app: database
spec:
  type: LoadBalancer
  ports:
    - port: 1433
      targetPort: 1433
  selector:
    app: microservice-seguridad
    name: mssql-pod
